### ISSUE TITLE
[BUG] File exists

### ISSUE THREAD

**Issue by martindevora** [PlanetHunters/tkmatrix#26]
WARNING:astroquery:The "exact" method is not yet implemented for rectangular apertures -- using "subpixel" method with "subpixels=32"
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fardeau/.local/lib/python3.8/site-packages/tkmatrix/__main__.py", line 95, in <module>
    inject_dir = ir.inject(matrix_user_properties["PHASES"], matrix_user_properties["MIN_PERIOD"],
  File "/home/fardeau/.local/lib/python3.8/site-packages/tkmatrix/tkmatrix_class.py", line 105, in inject
    os.mkdir(inject_dir)
FileExistsError: [Errno 17] File exists: './/.//TIC362103375_ir_2/'

**Comment by martindevora** [comment]
Already fixed.
