### ISSUE TITLE
Enabling SIMPLE_OSCILLATIONS_REDUCTION algorithm fails to produce a_tls_report

### ISSUE THREAD

**Issue by toribonidie** [PlanetHunters/tkmatrix#31]
I am running MATRIX on a yaml file with SIMPLE_OSCILLATIONS_REDUCTION enabled, and it is not producing a report. I am copying the exact error at the end of this message. I am also attaching my yaml file (I reduced the number of scenarios it evaluates so that it does not take long to run)
[KIC11235672.txt](https://github.com/PlanetHunters/tkmatrix/files/13591804/KIC11235672.txt)

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tkmatrix/tkmatrix_class.py", line 433, in recovery
    self.retrieve_object_data_for_recovery(inject_dir + "/", inject_dir + file)
  File "/usr/local/lib/python3.10/site-packages/tkmatrix/tkmatrix_class.py", line 140, in retrieve_object_data_for_recovery
    self.lc_build = self.lcbuilder.build(self.object_info, inject_dir, self.cache_dir, self.cores)
  File "/usr/local/lib/python3.10/site-packages/lcbuilder/lcbuilder_class.py", line 134, in build
    flatten_flux = self.__reduce_simple_oscillations(object_dir, object_info.mission_id(), clean_time,
  File "/usr/local/lib/python3.10/site-packages/lcbuilder/lcbuilder_class.py", line 278, in __reduce_simple_oscillations
    self.__plot_pulsation_fit(sa_dir, object_id, time, flux, fit_flux, period, number)
  File "/usr/local/lib/python3.10/site-packages/lcbuilder/lcbuilder_class.py", line 337, in __plot_pulsation_fit
    axs.set_title(object_id + " stellar activity P=" + str(round(period, 6)) + "d")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/tkmatrix/__main__.py", line 163, in <module>
    ir.plot_results(target, inject_dir, period_grid, radius_grid, period_grid_geom=matrix_user_properties["PERIOD_GRID_GEOM"],
  File "/usr/local/lib/python3.10/site-packages/tkmatrix/tkmatrix_class.py", line 502, in plot_results
    df = pd.read_csv(inject_dir + filename, float_precision='round_trip', sep=',',
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './/KIC11235672_ir//a_tls_report.csv'
File not valid: P4.0_R5.0_123.20577592509169.csv
`

**Comment by martindevora** [comment]
Checking, I was able to reproduce it. I'll let you know as soon as I find the root cause and prepare a fix.

**Comment by martindevora** [comment]
Found it. I'm preparing a new release for it to be fixed.

**Comment by martindevora** [comment]
The new version is published. Let me know in case it doesn't fix the issues.
